services:
  mysql:
    image: mysql:8.0
    container_name: ticketing_db_local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ticketing_db
      MYSQL_USER: ticketing_user
      MYSQL_PASSWORD: ticketing_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/01_schemas.sql:/docker-entrypoint-initdb.d/01_schemas.sql:ro
      - ./backend/sql/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql:ro
      - ./backend/sql/03_admin_seed.sql:/docker-entrypoint-initdb.d/03_admin_seed.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
