export const COUNTRY_CODES = [
  { name: 'Argentina', dialCode: '+54' },
  { name: 'Australia', dialCode: '+61' },
  { name: 'Bolivia', dialCode: '+591' },
  { name: 'Brasil', dialCode: '+55' },
  { name: 'Canada', dialCode: '+1' },
  { name: 'Chile', dialCode: '+56' },
  { name: 'China', dialCode: '+86' },
  { name: 'Colombia', dialCode: '+57' },
  { name: 'Costa Rica', dialCode: '+506' },
  { name: 'Cuba', dialCode: '+53' },
  { name: 'Ecuador', dialCode: '+593' },
  { name: 'El Salvador', dialCode: '+503' },
  { name: 'España', dialCode: '+34' },
  { name: 'Estados Unidos', dialCode: '+1' },
  { name: 'Francia', dialCode: '+33' },
  { name: 'Guatemala', dialCode: '+502' },
  { name: 'Honduras', dialCode: '+504' },
  { name: 'Italia', dialCode: '+39' },
  { name: 'Jamaica', dialCode: '+1876' },
  { name: 'Japón', dialCode: '+81' },
  { name: 'México', dialCode: '+52' },
  { name: 'Nicaragua', dialCode: '+505' },
  { name: 'Países Bajos', dialCode: '+31' },
  { name: 'Panamá', dialCode: '+507' },
  { name: 'Paraguay', dialCode: '+595' },
  { name: 'Perú', dialCode: '+51' },
  { name: 'Portugal', dialCode: '+351' },
  { name: 'Puerto Rico', dialCode: '+1787' },
  { name: 'Reino Unido', dialCode: '+44' },
  { name: 'República Dominicana', dialCode: '+1809' },
  { name: 'Rusia', dialCode: '+7' },
  { name: 'Turquía', dialCode: '+90' },
  { name: 'Uruguay', dialCode: '+598' },
  { name: 'Venezuela', dialCode: '+58' },
]
